= Hosting Http Servers
Doc Writer <christian.popescu@outlook.com>
v 1.0, 2025-05-30
:sectnums:
:toc:
:toclevels: 5

== Introduction

This document is about options available to host HTTP Servers.

In my case it's about hosting locally servers to test or to keep some private sites (wiki, docs, etc.).


== Market share of different Web Servers



https://w3techs.com/technologies/overview/web_server[W3tech - web servers market share]

As of 05/2025

* Nginx – 33.8% of websites

* Apache – 26.2%

* Cloudflare Server – 23.8%

* LiteSpeed – 14.6%

* Node.js – 4.5%

* Microsoft IIS – 3.9%

* Envoy – 1.4%

* Google Servers – 0.8%

* Caddy – 0.3%

Tengine, Cowboy, Kestrel – 0.1% each


== Solutions available

=== Python (Built-in HTTP Server)

If you have Python 3, navigate to the site directory and run:

[source, bash]
----
cd the-site
python -m http.server 8080
----

Now your the site is available at http://localhost:8080.

=== Node.js (http-server)

The following package should be installed :

[source, bash]
----
npm install -g http-server
----

[source, bash]
----
cd the-site
http-server -p 8080
----

=== Nginx

You can install Nginx on Windows by following these steps:

1. Download Nginx
Go to the official Nginx download page.

Download the latest mainline version (recommended for new features) or the stable version.

2. Extract the Files

    Locate the downloaded .zip file.

    Extract it to a directory, e.g., C:\nginx.

3. Start Nginx

    Open Command Prompt as Administrator.

    Navigate to the extracted folder:

    cd C:\nginx
    start nginx.exe
4. Verify installation

    Open a browser and go to http://localhost. If installed correctly, you should see the Nginx welcome page.

5. Manage Nginx

    Stop Nginx: nginx -s stop

    Quit Nginx gracefully: nginx -s quit

    Reload configuration: nginx -s reload

    Reopen log files: nginx -s reopen

6. Add new site

The site deployed on D:\KnowledgeManagement\docs is published on http://localhost:8080

    server {
    listen 8080;
    server_name KnowledgeManagement.local;
    root D:\KnowledgeManagement\docs;
    index index.html;
    }