= Miscellaneous
Doc Writer <christian.popescu@outlook.com>
v 1.0, 2019-12-22
:sectnums:
:toc:
:toclevels: 5

== Introduction
It's about diferents subjects to organize latter

== SYS2 + build GCC

*MSYS2* is a software distro and building platform for Windows.

At its core is an independent rewrite of MSYS, based on modern Cygwin (POSIX compatibility layer) and MinGW-w64 with the aim of better interoperability with native Windows software. 
It provides a bash shell, Autotools, revision control systems and the like for building native Windows applications using MinGW-w64 toolchains.

Site: https://www.msys2.org/[Home page of msys2 org] 


=== Simplified installation procedure

1. Download and run the installer - "x86_64" for 64-bit, "i686" for 32-bit Windows.
 
2. Update the package database and core system packages with:
	
	pacman -Syu
 
 
 3. close MSYS2 (close window not exit or quit), run it again from Start menu. Syncrhonize the rest.
 
 	pacman -Su
 	
 4. Add different tools
 
	 pacman -S --needed base-devel perl ruby python2 wget p7zip
 

